package src.View;

import javax.swing.*;
import java.awt.*;

public class CalculatorGui {
    public JFrame frame = new JFrame();
    public JPanel principalPanel = new JPanel();
    public JLabel firstPolynomial = new JLabel("First Model.Polynomial = ");
    public JLabel secondPolynomial = new JLabel("Second Model.Polynomial = ");
    public JLabel result = new JLabel("Result = ");
    public JTextField enterFirstPolynomial = new JTextField(10);
    public JTextField enterSecondPolynomial = new JTextField(10);
    public JTextField resultTxt = new JTextField(10);
    public JPanel polynomialPanel = new JPanel();
    public GridBagConstraints c = new GridBagConstraints();
    public JPanel operationPanel = new JPanel();
    public JButton addButton = new JButton("Add");
    public JButton substractButton = new JButton("Substract");
    public JButton multiplicateButton = new JButton("Multiplicate");
    public JButton divideButton = new JButton("Divide");
    public JButton derivateButton = new JButton("Derivate");
    public JButton integrationButton = new JButton("Integrate");
    public JPanel numbersPanel = new JPanel();
    public JButton zero = new JButton("0");
    public JButton one = new JButton("1");
    public JButton two = new JButton("2");
    public JButton three = new JButton("3");
    public JButton four = new JButton("4");
    public JButton five = new JButton("5");
    public JButton six = new JButton("6");
    public JButton seven = new JButton("7");
    public JButton eight = new JButton("8");
    public JButton nine = new JButton("9");
    public JPanel mathematicalSignsPanel = new JPanel();
    public JButton plusButton = new JButton("+");
    public JButton minusButton = new JButton("-");
    public JButton divideBarButton = new JButton("/");
    public JButton multiplicationButton = new JButton("*");
    public JButton powButton = new JButton("^");
    public JButton dotButton = new JButton(".");
    public JButton xButton = new JButton("x");
    public JButton equalsButton = new JButton("=");
    public JButton deleteButton = new JButton("DEL");
   public void setButtons(){
       zero.setFocusable(false);
       one.setFocusable(false);
       two.setFocusable(false);
       three.setFocusable(false);
       four.setFocusable(false);
       five.setFocusable(false);
       six.setFocusable(false);
       seven.setFocusable(false);
       eight.setFocusable(false);
       nine.setFocusable(false);
       plusButton.setFocusable(false);
       minusButton.setFocusable(false);
       divideBarButton.setFocusable(false);
       multiplicationButton.setFocusable(false);
       powButton.setFocusable(false);
       dotButton.setFocusable(false);
       xButton.setFocusable(false);
       deleteButton.setFocusable(false);
       addButton.setFocusable(false);
    }
    public CalculatorGui() {
        frame.setSize(400, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        principalPanel.setBackground(Color.LIGHT_GRAY);
        polynomialPanel.setBackground(Color.LIGHT_GRAY);
        polynomialPanel.setLayout(new GridBagLayout());

        c.fill = GridBagConstraints.PAGE_START;
        c.gridx = 0;
        c.gridy = 0;
        polynomialPanel.add(firstPolynomial, c);
        c.gridx = 1;
        c.gridy = 0;
        polynomialPanel.add(enterFirstPolynomial, c);
        c.fill = GridBagConstraints.PAGE_START;
        c.gridx = 0;
        c.gridy = 1;
        polynomialPanel.add(secondPolynomial, c);
        c.fill = GridBagConstraints.PAGE_START;
        c.gridx = 1;
        c.gridy = 1;
        polynomialPanel.add(enterSecondPolynomial, c);
        c.gridx = 0;
        c.gridy = 2;
        polynomialPanel.add(result, c);
        c.gridx = 1;
        c.gridy = 2;
        polynomialPanel.add(resultTxt, c);
        principalPanel.add(polynomialPanel);

        operationPanel.setLayout(new GridBagLayout());
        operationPanel.setBackground(Color.LIGHT_GRAY);

        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.gridy = 0;
        operationPanel.add(addButton, c);
        c.gridx = 1;
        c.gridy = 0;
        operationPanel.add(substractButton, c);
        c.gridx = 0;
        c.gridy = 1;
        operationPanel.add(multiplicateButton, c);
        c.gridx = 1;
        c.gridy = 1;
        operationPanel.add(divideButton, c);
        c.gridx = 0;
        c.gridy = 2;
        operationPanel.add(derivateButton, c);
        c.gridx = 1;
        c.gridy = 2;
        operationPanel.add(integrationButton, c);
        Component rigidArea = Box.createRigidArea(new Dimension(400, 15));
        principalPanel.add(rigidArea);
        principalPanel.add(operationPanel);
        numbersPanel.setLayout(new GridBagLayout());
        numbersPanel.setBackground(Color.LIGHT_GRAY);
        c.gridx = 0;
        c.gridy = 0;
        numbersPanel.add(one, c);
        c.gridx = 1;
        c.gridy = 0;
        numbersPanel.add(two, c);
        c.gridx = 2;
        c.gridy = 0;
        numbersPanel.add(three, c);
        c.gridx = 0;
        c.gridy = 1;
        numbersPanel.add(four, c);
        c.gridx = 1;
        c.gridy = 1;
        numbersPanel.add(five, c);
        c.gridx = 2;
        c.gridy = 1;
        numbersPanel.add(six, c);
        c.gridx = 0;
        c.gridy = 2;
        numbersPanel.add(seven, c);
        c.gridx = 1;
        c.gridy = 2;
        numbersPanel.add(eight, c);
        c.gridx = 2;
        c.gridy = 2;
        numbersPanel.add(nine, c);
        c.gridx = 1;
        c.gridy = 3;
        numbersPanel.add(zero, c);
        Component rigidArea2 = Box.createRigidArea(new Dimension(400, 15));
        principalPanel.add(rigidArea2);
        principalPanel.add(numbersPanel);

        mathematicalSignsPanel.setLayout(new GridBagLayout());
        mathematicalSignsPanel.setBackground(Color.LIGHT_GRAY);

        c.gridx = 0;
        c.gridy = 0;
        mathematicalSignsPanel.add(plusButton, c);
        c.gridx = 1;
        c.gridy = 0;
        mathematicalSignsPanel.add(minusButton, c);
        c.gridx = 2;
        c.gridy = 0;
        mathematicalSignsPanel.add(multiplicationButton, c);
        c.gridx = 0;
        c.gridy = 1;
        mathematicalSignsPanel.add(divideBarButton, c);
        c.gridx = 1;
        c.gridy = 1;
        mathematicalSignsPanel.add(powButton, c);
        c.gridx = 2;
        c.gridy = 1;
        mathematicalSignsPanel.add(dotButton, c);
        c.gridx = 0;
        c.gridy = 2;
        mathematicalSignsPanel.add(xButton, c);
        c.gridx = 1;
        c.gridy = 2;
        mathematicalSignsPanel.add(equalsButton, c);
        c.gridx = 2;
        c.gridy = 2;
        mathematicalSignsPanel.add(deleteButton, c);
        principalPanel.add(mathematicalSignsPanel);
        frame.add(principalPanel);
        frame.setResizable(false);
        frame.setVisible(true);

    }
}
